spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutornow
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    co.edu.epi.tutornow: DEBUG
    org.springframework.security: DEBUG
